### PR TITLE
[maintain] Use yarn instead of npm

### PR DESCRIPTION
**Pull request by Fohlen**
Tested it. Running `inexor-flex` is the same quality. Now I don't know. We just need to test publishing and see if it works...

### CODE REVIEW

**Comment by Croydon** [comment]
This needs a rebase now (sorry).

Also does Node Security uses the package-lock.json for it's scanning? Seems like it, otherwhise this won't get green lights. Can we somehow change it to scan the package.json?

**Comment by Fohlen** [comment]
@Croydon surprisingly enough it does recognise the `"resolves"` key and uses yarn to create a `yarn.lock` at runtime, which is then used to look up dependency issues. So, pretty much, `package-lock.json` can be deleted, `yarn.lock` is also not necessary, only `package.json` is, which is amazing by the way 👍

**Comment by Croydon** [comment]
If that is the case, how did this get green lights? It still uses the same dependencies, therefore it should detect the same security issues.

**Comment by Croydon** [comment]
yarn supports global overrides, hoek >=5.0.3 solves the issues.

**Comment by Croydon** [comment]
Feel free to merge this now if you want.

**Pull request merged**
